### ISSUE TITLE
npm ERR! Exit status 1

### ISSUE THREAD

**Issue by omerqw23451** [PcapPlusPlus/pcapplusplus.github.io#27]
do the command npm start and i get the error 

import logger from '@docusaurus/logger';
       ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcapplusplus-github-io@0.0.0 start: `docusaurus start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcapplusplus-github-io@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-23T18_14_43_413Z-debug.log

**Comment by seladb** [comment]
I think you should run `npm ci` first to install all dependencies

**Comment by seladb** [comment]
Can you please share the entire log of how you fetch the code, install the dependencies and run the app?

**Comment by seladb** [comment]
@omerqw23451 did you manage to solve the issue?

**Comment by seladb** [comment]
I'm closing this issue now due to inactivity. Please reopen if needed
